# Generated by Django 5.2.4 on 2025-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image',
        ),
        migrations.AddField(
            model_name='snack',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.FloatField(),
        ),
    ]
