# Generated by Django 5.2.4 on 2025-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_snack_image_snack_image_url_alter_snack_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image_url',
        ),
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snacks/'),
        ),
    ]
